server:
  port: 8888
  context-path: /
logging:
  file: /kation-cloud/logs/config/system.log  # 日志文件,绝对路径或相对路径
  path: /kation-cloud/logs/config  # 保存日志文件目录路径
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kationwcc/configuration.git
          username: kationwcc
          password: wcc110120
          search-paths: wccwin_config
          force-pull: true
        health:
          repositories:
            a-hello:
              label: master
              name: wccwin
              profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 60   # 发呆时间，即服务续约到期时间（缺省为90s）
    status-page-url-path: /info
    health-check-url-path:  /health
  client:
    healthcheck:
        enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://kation:123456@localhost:8761/eureka
security:
  basic:
    enabled: false